### PR TITLE
Bug fixed for remove old labels

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by strk** [comment]
Again: can you provide a testcase showing the need for a fix ?
BTW, do you know you can force-push to a branch associated with a PR rather than create a new PR ?

**Comment by lunny** [comment]
1. Don't know how to write the testcase
2. Don't want to use administrator power to push

**Comment by tboerger** [comment]
You don't need administrator power to do a force push on your feature branch

**Comment by tboerger** [comment]
Without testing it but I would say LGTM

**Comment by strk** [comment]
You get my trust-based LGTM too, but please try to think about ways to automate tests for bugs. None of us know how to, it probably needs to be invented and documented for others to be easier :)

**Pull request merged**
